ESPBAUD ?= 460800
FLASH_SPEED ?= 80
FLASH_SIZE ?= 16
PRINTF_SCANF_FLOAT_SUPPORT ?= 0
SPLIT_SECTIONS ?= 0

EXTRA_COMPONENTS=extras/dhcpserver extras/httpd extras/mbedtls extras/i2c

EXTRA_C_CXXFLAGS=-DLWIP_HTTPD_CGI=1 -DLWIP_DEBUG=1
EXTRA_CXXFLAGS=-std=gnu++11
